version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres
      
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: united_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: cd server && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: cd server && npm test

  deploy:
      machine:
        enabled: true
      steps:
        - run:
            name: Deploy Over SSH
            command: |
              ssh ubuntu@ec2-18-208-114-248.compute-1.amazonaws.com './deploy.sh'
  workflows:
    version: 2
    build-and-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
