version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres
      
      - image: circleci/10.6-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: united_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: cd server && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: cd server && npm test
