version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
      
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: united_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/server/package.json" }}
          - v1-dependencies-

      - run: cd server && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "/server/package.json" }}

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: cd server && npm test
