version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
      
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: united_test

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: cd server  && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: cd server && npm test
